-- ================================================================
-- Whiteboard Education: Accommodations Import
-- ================================================================

INSERT INTO public.accommodations (name, city, type, price_per_month, amenities, near_university_ids) VALUES
  ('Multimedia University Malaysia (MMU) Nearby Accommodation', 'Selangor', 'Apartment', 600, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'Multimedia University Malaysia (MMU)' LIMIT 1))),
  ('UCSI University Malaysia Nearby Accommodation', 'Kuala Lumpur', 'Apartment', 615, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'UCSI University Malaysia' LIMIT 1))),
  ('Taylor''s University Malaysia Nearby Accommodation', 'Selangor', 'Apartment', 630, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'Taylor''s University Malaysia' LIMIT 1))),
  ('APU University Malaysia Nearby Accommodation', 'Kuala Lumpur', 'Apartment', 645, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'APU University Malaysia' LIMIT 1))),
  ('UNITEN University Malaysia Nearby Accommodation', 'Selangor', 'Apartment', 660, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'UNITEN University Malaysia' LIMIT 1))),
  ('City University Malaysia Nearby Accommodation', 'Selangor', 'Apartment', 675, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'City University Malaysia' LIMIT 1))),
  ('Cyberjaya University Malaysia (UoC) Nearby Accommodation', 'Selangor', 'Apartment', 690, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'Cyberjaya University Malaysia (UoC)' LIMIT 1))),
  ('MAHSA University Malaysia Nearby Accommodation', 'Selangor', 'Apartment', 705, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'MAHSA University Malaysia' LIMIT 1))),
  ('SEGi University Malaysia Nearby Accommodation', 'Kuala Lumpur', 'Apartment', 735, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'SEGi University Malaysia' LIMIT 1))),
  ('Limkokwing University Malaysia Nearby Accommodation', 'Selangor', 'Apartment', 750, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'Limkokwing University Malaysia' LIMIT 1))),
  ('Infrastructure University Kuala Lumpur (IUKL) Nearby Accommodation', 'Selangor', 'Apartment', 765, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'Infrastructure University Kuala Lumpur (IUKL)' LIMIT 1))),
  ('INTI International University Malaysia Nearby Accommodation', 'Kuala Lumpur', 'Apartment', 780, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'INTI International University Malaysia' LIMIT 1))),
  ('UniKL University Malaysia Nearby Accommodation', 'Kuala Lumpur', 'Apartment', 795, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'UniKL University Malaysia' LIMIT 1))),
  ('Nottingham University Malaysia Nearby Accommodation', 'Selangor', 'Apartment', 840, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'Nottingham University Malaysia' LIMIT 1))),
  ('UTM University Malaysia Nearby Accommodation', 'Johor', 'Apartment', 885, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'UTM University Malaysia' LIMIT 1))),
  ('UTeM University Malaysia Nearby Accommodation', 'Malacca', 'Apartment', 900, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'UTeM University Malaysia' LIMIT 1))),
  ('Lincoln University College Nearby Accommodation', 'Selangor', 'Apartment', 915, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'Lincoln University College' LIMIT 1))),
  ('Sunway University Nearby Accommodation', 'Kuala Lumpur', 'Apartment', 945, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'Sunway University' LIMIT 1))),
  ('Management and Science University (MSU) Nearby Accommodation', 'Selangor', 'Apartment', 960, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'Management and Science University (MSU)' LIMIT 1))),
  ('UTM SPACE University Malaysia Nearby Accommodation', 'Johor', 'Apartment', 990, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'UTM SPACE University Malaysia' LIMIT 1))),
  ('University of Southampton Malaysia Nearby Accommodation', 'Johor', 'Apartment', 620, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'University of Southampton Malaysia' LIMIT 1))),
  ('Xiamen University Malaysia Campus Nearby Accommodation', 'Selangor', 'Apartment', 665, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'Xiamen University Malaysia Campus' LIMIT 1))),
  ('NILAI University Nearby Accommodation', 'Negeri Sembilan', 'Apartment', 710, '["WiFi","Air Conditioning","Security 24/7","Gym","Swimming Pool"]'::jsonb, jsonb_build_array((SELECT id FROM public.universities WHERE name = 'NILAI University' LIMIT 1)));
